### ISSUE TITLE
[Crash Report] Getting loads of crashes, have been asked to report here to have it fixed

### ISSUE THREAD

**Issue by NyarlathotepZERO** [Fabricators-of-Create/Porting-Lib#31] opened 2023-01-20 21:18 UTC
Getting loads of crashes, I've been told that these are crashes related to Create and its porting lib library. 
"at net.minecraft.class_1309.handler$zcg000$port_lib$spawnDropsTAIL(class_1309.java:5701)"

Here are a bunch of reports which relate to this.
https://pastebin.com/Q8MsqyXE
https://pastebin.com/KWkbAxLZ
https://pastebin.com/tbnGXDVR
https://pastebin.com/2a3rCp8F
https://pastebin.com/Atqw3Mnd
https://pastebin.com/taBTgiXD
https://pastebin.com/ybbde7TT

**Comment by TropheusJ** [comment] 2023-01-20 21:21
Duplicate of #29 
This crash is only present in newer, unstable versions of porting lib. Never install it manually unless you have a very good reason, it should always be included by the mods that use it.

**Closed as completed by TropheusJ** 2023-01-20 21:21 UTC

**Comment by itsdinkd** [comment] 2023-01-20 21:46
> Duplicate of #29 This crash is only present in newer, unstable versions of porting lib. Never install it manually unless you have a very good reason, it should always be included by the mods that use it.


A player of Another quality modpack opened this. 
The version that comes with Create does not work with Another Quality Modpack forcing curseforge usage of porting lib.  https://pastebin.com/k8gBr8mp

**Comment by itsdinkd** [comment] 2023-02-03 02:55
@TropheusJ just saw create was updated. Does the update contain the fix to spawnDropsTAIL?
